# Generated by Django 5.2.1 on 2026-03-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje o Millaje actual')),
                ('nivel_gasolina', models.CharField(choices=[('VACIO', 'Reserva / Vacío'), ('CUARTO', '1/4 de Tanque'), ('MEDIO', '1/2 Tanque'), ('TRESCUARTOS', '3/4 de Tanque'), ('LLENO', 'Tanque Lleno')], default='MEDIO', max_length=20)),
                ('motivo_ingreso', models.TextField(help_text='¿Qué reporta el cliente que le falla al vehículo?')),
                ('diagnostico_inicial', models.TextField(blank=True, help_text='Observación inicial del mecánico/recepcionista', null=True)),
                ('danos_previos', models.TextField(blank=True, help_text='Rayones, abolladuras, golpes, pintura en mal estado, etc.', null=True)),
                ('tiene_llanta_repuesto', models.BooleanField(default=False)),
                ('tiene_gata_herramientas', models.BooleanField(default=False)),
                ('tiene_radio', models.BooleanField(default=False)),
                ('tiene_documentos', models.BooleanField(default=False)),
                ('otros_objetos', models.CharField(blank=True, help_text='Ej: Lentes de sol, cargadores, etc.', max_length=255, null=True)),
                ('firma_cliente_text', models.CharField(blank=True, help_text='Nombre escrito como firma de conformidad del cliente.', max_length=100, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepcion', to='citas.cita')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='citas.vehiculo')),
            ],
            options={
                'verbose_name': 'Recepción de Vehículo',
                'verbose_name_plural': 'Recepciones de Vehículos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
