# Generated by Django 5.2.1 on 2026-03-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_alertainventario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='fecha_entrega_estimada',
            new_name='fecha_esperada',
        ),
        migrations.AlterUniqueTogether(
            name='detalleordencompra',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='numero',
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADA', 'Solicitada al Proveedor'), ('PARCIAL', 'Recibida Parcialmente'), ('COMPLETA', 'Recibida Completa'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='inventario.proveedor'),
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='cantidad',
        ),
    ]
