# Generated by Django 5.2.1 on 2026-03-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_cuentaproveedor_pagoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ofrecido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_proveedores', to='inventario.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_ofrecidos', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Precio de Proveedor',
                'verbose_name_plural': 'Precios de Proveedores',
                'ordering': ['producto', 'precio_ofrecido'],
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
